const TRANSLATIONS = {
  jp: {
    // 共通ナビ・ヘッダー
    'nav.top':          'トップ',
    'nav.builds':       '構築記事',
    'nav.regulation':   'レギュレーション',
    'nav.tournament':   '大会情報',
    'nav.beginner':     '初心者向け',
    'header.search':    '🔍　キーワード検索',
    'header.tagline':   'ポケモン構築紹介メディア',

    // トップバー
    'topbar.tagline': '⚡ ポケモン構築紹介専門メディア — エモンガに魅せられた人たちへ',

    // index.html ヒーロー
    'hero.tag':   '⚡ NEW POST — レギュレーションJ',
    'hero.h1':    '新しく生まれ変わった<em>構築紹介</em>サイト',
    'hero.desc':  '電気タイプの飛行ポケモン・エモンガを軸に据えた革新的な晴れパーティ。相手の裏をかく戦略で頂点を目指した全記録。',
    'hero.btn1':  '⚡ 記事を読む',
    'hero.btn2':  '構築記事一覧 →',

    // index.html セクション
    'section.featured': '注目の構築記事',
    'section.seeall':   'すべて見る →',
    'section.latest':   '最新の構築記事',
    'section.more':     'もっと見る →',

    // カテゴリタブ
    'cat.all':        'すべて',
    'cat.wcs':        'WCS2026',
    'cat.official':   '公式大会',
    'cat.grassroots': '草の根大会',
    'cat.online':     'オンライン',
    'cat.offline':    'オフライン',

    // 記事カード：article-wcs2026
    'art1.reg':    '⚡ レギュレーションJ',
    'art1.title':  '【WCS2026予選通過】エモンガ×カイオーガの電気雨パで世界を目指した構築全公開',
    'art1.desc':   'エモンガの「ふゆう」と電気技のシナジーを極限まで活かした構築。',
    'art1.author': 'エモ太郎 · 2026.05.01',

    // 記事カード：article-gorilla
    'art2.title': 'エモンガ×ゴリランダーの電気草パ — レート2000到達記念構築',
    'art2.meta':  '⚡ かみなり · 2026.04.28',

    // 記事カード：article-trick
    'art3.title': '【てるチャレ優勝】エモンガ入りトリックルーム構築の全貌',
    'art3.meta':  '⚡ emonga_game · 2026.04.22',

    // 記事カード：article-pjcs
    'art4.title': 'PJCS2026予選 上位使用構築まとめ — エモンガ採用率15%の衝撃',
    'art4.meta':  '編集部 · 2026.04.18',

    // 記事カード：article-training
    'art5.title': '【永久保存版】エモンガ完全育成論 — 努力値・持ち物・技構成の全パターン',
    'art5.meta':  'エモ博士 · 2026.04.10',

    // tournament.html
    'tournament.hero.h1':   '🏆 大会情報',
    'tournament.hero.desc': '公式大会・草の根大会の結果・スケジュールをまとめています。大会名をクリックすると詳細ページへ移動します。',
    'tournament.ongoing':   '📅 開催中・直近の大会',
    'tournament.recent':    '📊 最近の大会結果',

    // サイドバー
    'sidebar.about.title':   'New Emolgame とは',
    'sidebar.about.desc':    'エモンガを愛するプレイヤーたちによるポケモン構築紹介ブログ。ダブルバトルを中心に、バトルの最前線をお届けします。',
    'sidebar.ranking.title': '人気記事ランキング',
    'sidebar.tags.title':    'タグ',
    'sidebar.twitter.title': 'Twitter / X',
    'sidebar.twitter.desc':  '最新情報はこちら',
    'sidebar.twitter.btn':   'フォローする →',

    // フッター
    'footer.desc':     'エモンガに魅せられたポケモントレーナーたちが集うポケモン構築紹介メディア。',
    'footer.content':  'コンテンツ',
    'footer.siteinfo': 'サイト情報',
    'footer.contact':  'お問い合わせ',
    'footer.privacy':  'プライバシーポリシー',
    'footer.about':    '運営紹介',

    // 検索
    'search.placeholder': '記事タイトル・ポケモン名で検索…',
    'search.hint':        'キーワードを入力してください',
    'search.noresult':    'に一致する記事が見つかりませんでした',

    // builds.html
    'builds.hero.h1':   '📖 構築記事',
    'builds.hero.desc': '歴代の構築記事をまとめています。レギュレーション・大会別に絞り込めます。',
    'builds.section':   '📋 すべての構築記事',

    // regulation.html
    'reg.hero.h1':   '📋 レギュレーション',
    'reg.hero.desc': '現行・過去のレギュレーションをまとめています。',

    // beginner.html
    'beginner.hero.h1':   '🔰 初心者向けガイド',
    'beginner.hero.desc': 'ダブルバトルをはじめたい方向けの入門ガイドです。',

    // article 共通
    'article.back':               '← 記事一覧に戻る',
    'article.breadcrumb.builds':  '構築記事',
    'article.concept':            '構築コンセプト',
    'article.members':            '構築メンバー',
    'article.strategy':           '立ち回り',
    'article.results':            '大会戦績',
    'article.summary':            'まとめ',

    // バッジ共通
    'badge.regj':     'Reg.J',
    'badge.team':     '構築',
    'badge.event':    '大会',
    'badge.official': '公式大会',
    'badge.wcs':      'WCS2026',
    'badge.iku':      '育成論',
    'badge.begin':    '入門',

    // index.html サイドバー stats
    'sidebar.stats.builds':    '構築記事',
    'sidebar.stats.events':    '大会結果',
    'sidebar.stats.pv':        '月間PV',
    'sidebar.stats.followers': 'フォロワー',

    // builds.html 注目カード
    'builds.featured.head':   '注目の構築',
    'builds.featured.badge':  '🏆 WCS2026 予選',
    'builds.featured.reg':    '⚡ レギュレーションJ',
    'builds.featured.title':  '【WCS2026予選通過】エモンガ×カイオーガの電気雨パ構築',
    'builds.featured.desc':   'エモンガの「ふゆう」と「でんきエンジン」を活かし、カイオーガの「あまごい」下でかみなりを連発する構築。選出・立ち回りを徹底解説します。',
    'builds.featured.author': 'エモ太郎 · 2026.05.01',
    'builds.info':            '💡 <strong>構築記事の読み方：</strong>各記事では採用理由・努力値・技構成・選出パターンを解説しています。初心者の方は先に<a href="beginner.html" style="color:var(--sky-dark);font-weight:600;">初心者向けページ</a>をご覧ください！',

    // builds.html 記事カード
    'builds.card1.title': 'エモンガ×ゴリランダーの電気草パ — レート2000到達記念',
    'builds.card2.title': '【てるチャレ優勝】エモンガ入りトリックルーム構築の全貌',
    'builds.card3.title': 'PJCS2026予選 上位使用構築まとめ — エモンガ採用率15%の衝撃',
    'builds.card4.title': '【永久保存版】エモンガ完全育成論 — 努力値・持ち物・技構成の全パターン',
    'builds.card5.title': 'WCS2026出場権獲得！エモンガ軸バランス構築の全記録',
    'builds.card6.title': 'エモンガ×ハバタクカミの電気フェアリー構築 — シーズン最終2100',

    // builds.html サイドバー
    'builds.sidebar.about':      '構築記事について',
    'builds.sidebar.about.desc': '実際に対戦で使った構築を、選出・立ち回り・反省点まで丁寧に解説しています！',
    'builds.sidebar.tags':       'タグで絞り込む',
    'builds.twitter.req':        '構築のリクエストはTwitterへ！',
    'builds.cta':                '構築記事は随時追加中！Twitterでも最新情報を発信しています。',

    // regulation.html 本文・サイドバー追加キー
    'reg.breadcrumb':            'トップ > レギュレーション',
    'reg.info':                  '⚡ <strong>エモンガはレギュレーションJでも使用可能です！</strong>でんき/ひこうタイプの唯一無二の存在として注目されています。',
    'reg.current.head':          '現行レギュレーション',
    'reg.regj.title':            '🔥 レギュレーションJ（現行）',
    'reg.regj.status':           'NOW',
    'reg.regj.desc':             'ポケモンスカーレット・バイオレットの最新レギュレーション。パラドックスポケモンや準伝説ポケモンが一部解禁されており、多彩な構築が生まれています。エモンガは「でんきエンジン」特性を活かした構築が注目されています。',
    'reg.regj.date':             '📅 2026年1月〜',
    'reg.regj.format':           '👥 ダブルバトル',
    'reg.regj.emolga':           '⚡ エモンガ使用可',
    'reg.regj.wcs':              '🏆 WCS2026対応',
    'reg.emolga.head':           'エモンガ採用のポイント',
    'reg.emolga.name':           'エモンガ（No.587）',
    'reg.emolga.types':          'でんき・ひこうタイプ / ふゆう・せいでんき・でんきエンジン',
    'reg.type.electric':         'でんき',
    'reg.type.flying':           'ひこう',
    'reg.table.stat':            'ステータス',
    'reg.table.base':            '種族値',
    'reg.table.note':            '特徴',
    'reg.stat.hp':               'HP',
    'reg.stat.atk':              'こうげき',
    'reg.stat.def':              'ぼうぎょ',
    'reg.stat.spa':              'とくこう',
    'reg.stat.spd':              'とくぼう',
    'reg.stat.spe':              'すばやさ',
    'reg.emolga.trait':          'すばやさ103はそこそこ速い。「でんきエンジン」で電気技を受けると攻撃力が2段階アップするのが最大の魅力！味方のかみなりを受けて全抜きを狙う戦術が強力です。',
    'reg.past.head':             '過去のレギュレーション',
    'reg.status.past':           '終了',
    'reg.regi.title':            'レギュレーションI',
    'reg.regi.desc':             'パラドックスポケモンが解禁されたレギュレーション。エモンガはレイジングボルトとのシナジーで活躍する場面が多かったです。',
    'reg.regi.date':             '📅 2025年6月〜12月',
    'reg.regi.emolga':           '⚡ エモンガ使用可',
    'reg.regh.title':            'レギュレーションH',
    'reg.regh.desc':             '禁止伝説が解禁されたレギュレーション。カイオーガとのコンビでエモンガが大きく注目されました。',
    'reg.regh.date':             '📅 2025年1月〜5月',
    'reg.regh.emolga':           '⚡ エモンガ使用可',
    'reg.cta':                   '構築記事を見る →',
    'reg.sidebar.quickref':      'レギュレーション早見表',
    'reg.sidebar.quickref.desc': 'エモンガは全レギュレーションで使用可能です！',
    'reg.sidebar.rules':         '現行ルール',
    'reg.rule.allowed':          '✅ 使用可能：レギュレーションJ対応ポケモン',
    'reg.rule.banned':           '❌ 禁止：一部の禁止伝説',
    'reg.rule.format':           '👥 形式：ダブルバトル',
    'reg.rule.time':             '⏱️ 持ち時間：7分',
    'reg.sidebar.related':       '関連ページ',
    'reg.link.builds':           '→ Reg.J対応構築一覧',
    'reg.link.tournament':       '→ 大会情報・スケジュール',
    'reg.link.beginner':         '→ ルールの基本を学ぶ',
    'reg.twitter.desc':          'ルール変更もTwitterで速報！',

    // beginner.html 本文・サイドバー追加キー
    'beg.breadcrumb':            'トップ > 初心者向け',
    'beg.guide.title':           '⚡ エモンガと一緒に強くなろう！',
    'beg.guide.desc':            '「ポケモンのダブルバトルって難しそう…」と思っていませんか？大丈夫！このページでは基礎からわかりやすく解説します。まずはエモンガの魅力を知るところから始めましょう！',
    'beg.steps.head':            '🚀 ダブルバトル入門 5ステップ',
    'beg.step1.title':           'ダブルバトルとは？',
    'beg.step1.desc':            'ダブルバトルは、お互いに2匹ずつポケモンを場に出して戦う形式です。シングルバトルと違い、<strong>2匹の連携</strong>が重要になります。たとえばエモンガが「かみなり」を放ち、味方が「でんきエンジン」で強化される…といったコンビが生まれます！',
    'beg.step2.title':           'パーティ（構築）を作ろう',
    'beg.step2.desc':            '試合に持っていける6匹のポケモンを「パーティ」と言います。その中から選出する4匹を選び、実際に戦うのは2匹ずつ。タイプのバランスや役割分担を意識してみましょう！エモンガはでんき/ひこうタイプで、多くの構築で活躍できます。',
    'beg.step3.title':           '努力値・個体値を理解しよう',
    'beg.step3.desc':            'ポケモンには「努力値（EV）」と「個体値（IV）」があります。育成次第でステータスが大きく変わります！エモンガのおすすめ努力値は<strong>こうげきやとくこうに252・すばやさに252</strong>の型が基本です。このサイトの育成論記事で詳しく解説しています！',
    'beg.step4.title':           '天候・フィールド効果を覚えよう',
    'beg.step4.desc':            '「あまごい（雨）」「にほんばれ（晴れ）」などの天候は、技の威力や特定の戦術に大きく影響します。エモンガ×カイオーガの「雨パ」では、あまごいで<strong>かみなりの命中率が100%</strong>になる！こういった組み合わせを知ることで構築の幅が広がります。',
    'beg.step5.title':           '実際に対戦してみよう！',
    'beg.step5.desc':            'ランクバトルやオンライン大会に参加してみましょう！最初は負けることも多いですが、それが一番の上達の近道です。<strong>このサイトの構築記事</strong>を参考にしながら、自分だけのパーティを作り上げていきましょう！',
    'beg.qa.head':               '❓ よくある質問（Q&A）',
    'beg.qa1.q':                 'エモンガって強いんですか？',
    'beg.qa1.a':                 '種族値は決して高くないですが、「でんきエンジン」という特性が非常にユニークです！味方の電気技を受けることで攻撃力が2段階アップし、爆発的な火力を出せます。使いこなせば対戦でも十分に活躍できます⚡',
    'beg.qa2.q':                 '構築記事は初心者でも読めますか？',
    'beg.qa2.a':                 'このサイトでは、できるだけわかりやすい言葉で解説するように心がけています。専門用語が出てきた場合はこのページのQ&Aで解説していますので、ぜひ参考にしてみてください！',
    'beg.qa3.q':                 '「選出」「立ち回り」ってどういう意味？',
    'beg.qa3.a':                 '「選出」は6匹のパーティから実際に使う4匹を選ぶことです。「立ち回り」は試合中のターンごとの行動の判断のことを指します。構築記事では「このポケモンに対してはこう選出する」「序盤はこう動く」などを詳しく解説しています！',
    'beg.qa4.q':                 'レギュレーションって何ですか？',
    'beg.qa4.a':                 '公式大会で使用できるポケモンのルールのことです。現在は「レギュレーションJ」が最新で、使えるポケモンが決まっています。エモンガはすべてのレギュレーションで使用可能です！詳しくは<a href="regulation.html" style="color:var(--sky-dark);">レギュレーションページ</a>をご覧ください。',
    'beg.qa5.q':                 '大会に出るにはどうすれば良いですか？',
    'beg.qa5.a':                 '公式大会はポケモンの公式アプリ「Pokémon HOME」や「ポケモン トレーナーズウェブサイト」から参加登録できます。草の根大会は主催者のTwitterやDiscordで参加方法が告知されます。このサイトの<a href="tournament.html" style="color:var(--sky-dark);">大会情報ページ</a>でも情報をまとめています！',
    'beg.articles.head':         '📚 初心者向けおすすめ記事',
    'beg.rec1.title':            '【永久保存版】エモンガ完全育成論 — 努力値・持ち物・技構成の全パターン',
    'beg.rec2.title':            'はじめてのダブルバトル！エモンガで勝てる初心者向け構築',
    'beg.cta':                   'すべての構築記事を見る →',
    'beg.sidebar.welcome':       'はじめての方へ',
    'beg.sidebar.welcome.desc':  'わからないことはTwitterでも気軽に質問してください！エモンガ好きが集まるフレンドリーなコミュニティです⚡',
    'beg.sidebar.toc':           '入門ガイド目次',
    'beg.toc1':                  '① ダブルバトルとは？',
    'beg.toc2':                  '② パーティを作ろう',
    'beg.toc3':                  '③ 努力値・個体値',
    'beg.toc4':                  '④ 天候・フィールド効果',
    'beg.toc5':                  '⑤ 実際に対戦しよう！',
    'beg.sidebar.related':       '関連ページ',
    'beg.link.builds':           '→ 構築記事を読む',
    'beg.link.regulation':       '→ レギュレーション確認',
    'beg.link.tournament':       '→ 大会情報',
    'beg.twitter.title':         '質問はTwitterへ！',
    'beg.twitter.desc':          '初心者の質問も大歓迎です！',

    // ポケモン名（poke.）
    'poke.emolga':        'エモンガ',
    'poke.kyogre':        'カイオーガ',
    'poke.volcarona':     'ウルガモス',
    'poke.landorus':      'ランドロス（霊獣）',
    'poke.gardevoir':     'サーナイト',
    'poke.incineroar':    'ガオガエン',
    'poke.rillaboom':     'ゴリランダー',
    'poke.urshifu':       'ウーラオス（いちげき）',
    'poke.urshifurapid':  'ウーラオス（れんげき）',
    'poke.porygon2':      'ポリゴン2',
    'poke.torkoal':       'コータス',
    'poke.mimikyu':       'ミミッキュ',
    'poke.rhyperior':     'ドサイドン',
    'poke.fluttermane':   'ハバタクカミ',
    'poke.indeedee':      'インドラ',
    'poke.miraidon':      'ミライドン',

    // 技名（move.）
    'move.discharge':     'ほうでん',
    'move.thunderwave':   'でんじは',
    'move.acrobatics':    'アクロバット',
    'move.protect':       'まもる',
    'move.waterspout':    'しおふき',
    'move.surf':          'なみのり',
    'move.thunder':       'かみなり',
    'move.icywind':       'こごえるかぜ',
    'move.fireblast':     'だいもんじ',
    'move.gigadrain':     'ギガドレイン',
    'move.quiverdance':   'ちょうのまい',
    'move.earthquake':    'じしん',
    'move.rockslide':     'いわなだれ',
    'move.fly':           'そらをとぶ',
    'move.uturn':         'とんぼがえり',
    'move.psychic':       'サイコキネシス',
    'move.moonblast':     'ムーンフォース',
    'move.trickroom':     'トリックルーム',
    'move.flareblitz':    'フレアドライブ',
    'move.darkestlariat': 'DDラリアット',
    'move.knockoff':      'はたきおとす',
    'move.fakeout':       'ねこだまし',
    'move.woodhammer':    'ウッドハンマー',
    'move.grassyglide':   'グラスラィダー',
    'move.closecombat':   'インファイト',
    'move.encore':        'アンコール',
    'move.shadowball':    'シャドーボール',
    'move.bulldoze':      'じならし',
    'move.thunderbolt':   '１０まんボルト',
    'move.eruption':      'ふんか',
    'move.helpinghand':   'てだすけ',
    'move.triattack':     'トライアタック',
    'move.foulplay':      'イカサマ',
    'move.recover':       'じこさいせい',
    'move.shadowclaw':    'シャドークロー',
    'move.shadowsneak':   'かげうち',
    'move.stoneedge':     'ストーンエッジ',
    'move.iceshard':      'こおりのつぶて',
    'move.irontail':      'アイアンテール',
    'move.wildcharge':    'ワイルドボルト',
    'move.drillpeck':     'ドリルくちばし',
    'move.mysticalfire':  'マジカルフレイム',
    'move.wickedblow':    'あんこくきょうだ',
    'move.surgingstrikes':'すいりゅうれんだ',

    // 持ち物（item.）
    'item.focussash':   'きあいのタスキ',
    'item.choicespecs': 'こだわりメガネ',
    'item.lifeorb':     'いのちのたま',
    'item.choicescarf': 'こだわりスカーフ',
    'item.silkscarf':   'シルクのスカーフ',
    'item.assaultvest': 'とつげきチョッキ',
    'item.leftovers':   'たべのこし',
    'item.sitrus':      'オボンのみ',
    'item.miracleseed': 'きせきのタネ',
    'item.eviolite':    'しんかのきせき',

    // 特性（ability.）
    'ability.levitate':       'ふゆう',
    'ability.drizzle':        'あめふらし',
    'ability.flamebody':      'ほのおのからだ',
    'ability.intimidate':     'いかく',
    'ability.trace':          'トレース',
    'ability.blaze':          'もうか',
    'ability.grassysurge':    'グラスメイカー',
    'ability.drought':        'ひでり',
    'ability.protosynthesis': 'こだいかっせい',
    'ability.unseenfist':     'ふかしのこぶし',
    'ability.download':       'ダウンロード',
    'ability.disguise':       'ばけのかわ',
    'ability.solidrock':      'ハードロック',
    'ability.tangledfeet':    'ちどりあし',

    // テーブルヘッダー（共通）
    'table.pokemon': 'ポケモン',
    'table.item':    '持ち物',
    'table.ability': '特性',
    'table.moves':   '技構成',
    'table.evs':     '努力値',

    // article-wcs2026.html
    'wcs.title':    '【WCS2026予選通過】エモンガ×カイオーガの電気雨パで世界を目指した構築全公開',
    'wcs.badge1':   '🏆 WCS2026 予選',
    'wcs.badge2':   '⚡ レギュレーションJ',
    'wcs.badge3':   '電気雨パ',
    'wcs.breadcrumb': '【WCS2026予選通過】エモンガ×カイオーガの電気雨パで世界を目指した構築全公開',
    'wcs.concept.p': 'エモンガの特性「ふゆう」により地面技を無効化しつつ、カイオーガの「あまごい」で電気技を強化するという独自のシナジーを構築の核に据えました。雨天候下ではエモンガの「ほうでん」や「１０まんボルト」が実質的な火力増強を受けることはないものの、カイオーガの圧倒的な特殊火力と電気タイプの一貫性が相手のパーティを崩す起点となります。WCS2026の対面環境において、相手の想定外の動きを突いた構築です。',
    'wcs.strategy.p1.title': 'パターン1：エモンガ+カイオーガ 先発雨展開',
    'wcs.strategy.p1.desc':  '最も基本的な初手。カイオーガが「あまごい」を発動させる間、エモンガが「でんじは」でサポート。カイオーガの「かみなり」が雨天候下で命中100%になる点が最大の強み。相手のガオガエンにはエモンガの「アクロバット」を温存して対応する。',
    'wcs.strategy.p2.title': 'パターン2：ガオガエン+エモンガ ねこだまし封じ展開',
    'wcs.strategy.p2.desc':  '相手にねこだましを使われる前にガオガエンが先手を取り、エモンガを安全に動かす立ち回り。エモンガの「まもる」で身を守りつつ、裏からカイオーガを着地させるスイッチプランが有効。',
    'wcs.strategy.p3.title': 'パターン3：ランドロス+サーナイト 対トリル展開',
    'wcs.strategy.p3.desc':  '相手がトリックルーム展開を狙っている場合、ランドロスの「いかく」で物理方面を抑えつつ、サーナイトが「トリックルーム」を先に張って逆トリルとして利用する逆転策。',
    'wcs.strategy.p4.title': 'パターン4：ウルガモス+エモンガ 電炎コンビ',
    'wcs.strategy.p4.desc':  '後半の詰めに使う組み合わせ。ウルガモスが「ちょうのまい」で積んだ後、エモンガが「ほうでん」で追い打ちをかける形。ウルガモスの炎技とエモンガの電気技で広い範囲をカバーできる。',
    'wcs.results.box1.label': '予選成績（スイス9回戦）',
    'wcs.results.box2.label': '最終順位',
    'wcs.results.box3.label': 'WCS2026ポイント獲得',
    'wcs.results.box4.label': 'エモンガ選出率',
    'wcs.results.p':  '予選を7勝2敗でTOP16に滑り込み、本戦出場権を獲得。決勝トーナメントはベスト16止まりとなりましたが、WCSポイントを3点獲得しWorld Championship出場への足がかりとなりました。エモンガは78%の試合で選出され、その対面性能の高さを証明しました。',
    'wcs.summary.p':  'エモンガ×カイオーガという一見奇抜な組み合わせが、想像以上のシナジーを生み出しました。環境読みと準備の大切さを改めて実感した大会です。次はWCS本戦での活躍を目指し、更なる調整を続けていきます。エモンガと共に世界へ！',

    // article-gorilla.html
    'gorilla.title':    'エモンガ×ゴリランダーの電気草パ — レート2000到達記念構築',
    'gorilla.badge1':   '🌿 電気草パ',
    'gorilla.badge2':   '⚡ レギュレーションJ',
    'gorilla.badge3':   'レート2000達成',
    'gorilla.breadcrumb': 'エモンガ×ゴリランダーの電気草パ — レート2000到達記念構築',
    'gorilla.concept.p': 'エモンガとゴリランダーのタイプ補完を活かした「電気草パ」。ゴリランダーの特性「グラスメイカー」でグラスフィールドを展開し、草技を強化しながらエモンガの電気技で広範囲をカバーします。地面技をフィールドで軽減しつつ、電気・草の高い一貫性で相手の選出を絞らせる戦略です。シーズン中のランクマッチでレート2000という節目を達成できた記念の構築を全公開します。',
    'gorilla.strategy.p1.title': 'パターン1：ゴリランダー+エモンガ グラスフィールド展開',
    'gorilla.strategy.p1.desc':  'ゴリランダーがグラスメイカーでフィールドを展開しつつ、エモンガが「でんじは」でサポート。グラスフィールドにより地震のダメージが半減し、エモンガが相手の地面技を無効化する「ふゆう」と合わせて二重の安全地帯を構築。',
    'gorilla.strategy.p2.title': 'パターン2：ポリゴン2+ゴリランダー 耐久展開',
    'gorilla.strategy.p2.desc':  'ポリゴン2の「てだすけ」でゴリランダーの「グラスラィダー」を強化する型。しんかのきせきで耐久を確保したポリゴン2が盾になりつつ、ゴリランダーが強化された草技で相手を削る。',
    'gorilla.strategy.p3.title': 'パターン3：ウーラオス+ランドロス 対面詰め',
    'gorilla.strategy.p3.desc':  '序盤に相手の構築を把握してから後半に投入するコンビ。ランドロスの「いかく」で物理アタッカーを弱体化させ、ウーラオスが抜き確になった相手を一掃する強引な詰め展開。',
    'gorilla.summary.p': 'レート2000という目標を達成できたのは、グラスフィールドとエモンガの地面無効という組み合わせが環境に刺さったおかげです。ゴリランダーとエモンガの並びは対策されにくく、これからも磨き続けたい構築です。次の目標はレート2100！',

    // article-trick-room.html
    'trick.title':    '【てるチャレ優勝】エモンガ入りトリックルーム構築の全貌',
    'trick.badge1':   '🏆 てるチャレ優勝',
    'trick.badge2':   'トリックルーム',
    'trick.badge3':   '草の根大会',
    'trick.breadcrumb': '【てるチャレ優勝】エモンガ入りトリックルーム構築の全貌',
    'trick.concept.p': '「エモンガはトリックルーム構築には合わない」という常識を覆すために作った構築です。エモンガ自体はトリル下では動きにくいですが、トリル展開をサポートするポジションや、トリル外の通常ターンに活躍する役割を明確に分けることで、構築の歯車として機能させました。てるチャレ（てるアカウント主催チャレンジカップ）で全勝優勝を達成した記念の全公開です。',
    'trick.strategy.p1.title': 'パターン1：ミミッキュ+ポリゴン2 二枚看板トリル展開',
    'trick.strategy.p1.desc':  'ミミッキュが「ばけのかわ」で一発耐えてトリックルームを張り、ポリゴン2が「てだすけ」でドサイドンをサポート。二体がそれぞれトリルを打てるため相手からの妨害に強い。',
    'trick.strategy.p2.title': 'パターン2：エモンガ+ドサイドン 対面補助',
    'trick.strategy.p2.desc':  'トリル外のターン、エモンガが「でんじは」で相手を麻痺させつつドサイドンが叩く。エモンガの「アンコール」で相手の積み技や補助技をロックする動きが特に強力。',
    'trick.strategy.p3.title': 'パターン3：ハバタクカミ+エモンガ 逆縦断展開',
    'trick.strategy.p3.desc':  'トリルを返されたり妨害されたりした場合の保険として用意したプラン。ハバタクカミが高速で動き、エモンガが「でんじは」で速度コントロールしながら対面を有利に進める。',
    'trick.strategy.p4.title': 'パターン4：インドラ+ドサイドン 鈍足同士のシナジー',
    'trick.strategy.p4.desc':  'トリル下の主力コンビ。インドラの「じならし」で速度を下げ、ドサイドンが「じしん」で範囲を取る。インドラが麻痺したふりをして動く「ちどりあし」が相手の読みを外す。',
    'trick.results.box1.label': 'てるチャレ予選',
    'trick.results.box2.label': '最終成績',
    'trick.results.box3.label': '参加者数',
    'trick.results.box4.label': 'エモンガ選出率',
    'trick.results.p':  '参加者32名のてるチャレで予選から決勝まで全勝（6-0）での優勝を達成。エモンガは「でんじは」と「アンコール」が特に活躍し、相手の行動を縛る動きが随所に光りました。',
    'trick.summary.p':  'エモンガはトリルと相性が悪いと思われがちですが、補助役として非常に優秀でした。「アンコール」で相手の補助技を封じる動きが特に刺さり、優勝の最大の要因だったと思います。エモンガの可能性は無限大です！',

    // article-pjcs2026.html
    'pjcs.title':    'PJCS2026予選 上位使用構築まとめ — エモンガ採用率15%の衝撃',
    'pjcs.badge1':   '🏆 PJCS2026',
    'pjcs.badge2':   '大会まとめ',
    'pjcs.badge3':   'エモンガ採用率15%',
    'pjcs.breadcrumb': 'PJCS2026予選 上位使用構築まとめ — エモンガ採用率15%の衝撃',
    'pjcs.intro.h2':  'はじめに',
    'pjcs.intro.p':   '2026年4月に開催されたPokémon Japan Championship Series 2026（PJCS2026）予選大会の上位16名の使用構築データを編集部が独自集計しました。今回最も注目すべき結果は、エモンガの採用率が15%（上位16名中5名が採用）に達した点です。近年のダブルバトル環境でこれほど多くの上位プレイヤーがエモンガを採用したのは史上初とも言える数字であり、環境の変化を感じさせます。',
    'pjcs.overview.h2':  '大会概要',
    'pjcs.overview.box1.label': '参加者数',
    'pjcs.overview.box2.label': 'スイスラウンド数',
    'pjcs.overview.box3.label': '決勝トーナメント進出数',
    'pjcs.overview.box4.label': 'エモンガ採用率（上位16名）',
    'pjcs.usage.h2':   '上位採用ポケモン TOP10',
    'pjcs.usage.th1':  '順位',
    'pjcs.usage.th2':  'ポケモン',
    'pjcs.usage.th3':  '採用数（/16）',
    'pjcs.usage.th4':  '採用率',
    'pjcs.usage.note': '※エモンガは集計対象外の予備枠ポケモンを除くと実質10位以内にランクイン。過去最高順位となります。',
    'pjcs.emolga.h2':  'エモンガ採用5名の構築テーマ',
    'pjcs.emolga.th1': '順位',
    'pjcs.emolga.th2': 'プレイヤー名',
    'pjcs.emolga.th3': '構築テーマ',
    'pjcs.emolga.th4': 'エモンガの役割',
    'pjcs.results.box1.label': 'エモンガ採用者（上位16名中）',
    'pjcs.results.box2.label': 'エモンガ採用者の最高成績',
    'pjcs.results.box3.label': '前年比採用者増',
    'pjcs.results.box4.label': '上位採用率（過去最高）',
    'pjcs.results.p':  'エモンガ採用者の上位入賞率は非常に高く、5名中3名がTOP8に入賞しました。これは偶然ではなく、現環境のカイオーガ+ランドロス軸に対してエモンガの「ふゆう」と「でんじは」が刺さっていることを示しています。',
    'pjcs.summary.p':  'PJCS2026予選でエモンガが上位15%の採用率を記録したことは、ポケモン対戦史における新たな1ページです。長らく「使えないポケモン」と言われてきたエモンガが環境に食い込んできた今、エモンガを軸にした構築研究がより盛んになることを期待します。',

    // article-training.html
    'train.title':    '【永久保存版】エモンガ完全育成論 — 努力値・持ち物・技構成の全パターン',
    'train.badge1':   '永久保存版',
    'train.badge2':   '育成論',
    'train.badge3':   '初心者向け',
    'train.breadcrumb': '【永久保存版】エモンガ完全育成論 — 努力値・持ち物・技構成の全パターン',
    'train.base.h2':  'エモンガ基本データ',
    'train.base.p1':  'エモンガ（No.587）は電気・飛行タイプの二足歩行リス型ポケモン。特性「ふゆう」により地面技が完全無効となるのが最大の特長です。種族値合計472と控えめですが、素早さ103が光り、サポート役として幅広い構築に組み込めます。',
    'train.base.ability': '特性：ふゆう（地面タイプの技・じならし・どろかけを無効化）/ モーター（使わない）',
    'train.base.type': 'タイプ：でんき・ひこう',
    'train.ev.h2':    '努力値配分 全5パターン',
    'train.ev.p':     'エモンガの役割に応じた努力値配分を5パターン紹介します。',
    'train.ev.th.name':    'パターン名',
    'train.ev.th.rec':     '推奨度',
    'train.ev.th.usage':   '用途',
    'train.ev.build1.name': '最速アタッカー',
    'train.ev.build1.usage': '最速S・電気技火力最大',
    'train.ev.build2.name': 'サポート特化',
    'train.ev.build2.usage': 'でんじは・アンコール役',
    'train.ev.build3.name': '耐久寄りサポート',
    'train.ev.build3.usage': 'きあいのタスキ不要型',
    'train.ev.build4.name': '物理アタッカー',
    'train.ev.build4.usage': 'アクロバット・とんぼがえり',
    'train.ev.build5.name': '準速耐久型',
    'train.ev.build5.usage': '詰め構築・壁役',
    'train.item.h2':  '持ち物候補',
    'train.item1.name': 'きあいのタスキ ★最推奨',
    'train.item1.desc': 'HP1で耐えて行動できる。エモンガの低耐久を補い、確実に1回は動ける保険。サポート型・アタッカー型どちらにも採用できる万能アイテム。',
    'train.item2.name': 'でんきだま',
    'train.item2.desc': '「アクロバット」との組み合わせが目的。使用後に威力が2倍になるアクロバットが強力で、物理型エモンガの選択肢。ただし最初のターンは持っておく必要がある。',
    'train.item3.name': 'こだわりスカーフ',
    'train.item3.desc': '素早さを1.5倍に強化。最速エモンガのS103を更に伸ばし、環境の速いポケモンを上から叩ける。ただし技が固定されるデメリットがある。',
    'train.item4.name': 'いのちのたま',
    'train.item4.desc': '攻撃技の威力を1.3倍に強化。アタッカー型エモンガの選択肢で、電気技の火力を底上げする。HPが削れるデメリットをタスキと比較して採用を検討。',
    'train.item5.name': 'オボンのみ',
    'train.item5.desc': 'HPが半分以下になると回復するきのみ。タスキ不採用時の耐久補助として機能し、複数ターン生き残ることが重要なサポート型に向く。',
    'train.move.h2':       '技構成の全パターン',
    'train.move.main.h3':  'メイン技（電気・飛行）',
    'train.move.sub.h3':   '補助技',
    'train.move.th.name':  '技名',
    'train.move.th.type':  'タイプ',
    'train.move.th.cat':   '分類',
    'train.move.th.power': '威力',
    'train.move.th.acc':   '命中',
    'train.move.th.pri':   '優先度',
    'train.move.th.desc':  '説明',
    'train.move.discharge.desc': '全体攻撃・30%麻痺。ダブルバトルで両サイドに届く主力技。',
    'train.move.thunderbolt.desc': '単体電気技の主力。高威力・安定命中で使いやすい。',
    'train.move.thunder.desc': '雨天候下で命中100%。カイオーガとのシナジーで採用価値大。',
    'train.move.acrobatics.desc': '持ち物なし時に威力2倍。でんきだまを使用した後に威力110に。',
    'train.move.uturn.desc': '打った後に交代できる。スイッチ戦術と組み合わせて使う。',
    'train.move.thunderwave.desc': '相手を麻痺状態にする。素早さ1/2化で速い相手を抑制できる強力なサポート。',
    'train.move.encore.desc': '相手の直前の技を3ターン強制継続。積み技やトリル展開を封じる技。',
    'train.move.protect.desc': 'このターン全ての技を防ぐ。ダブルバトルで必須の生存・調整技。',
    'train.move.icywind.desc': '相手全体の素早さを1段階下げる。スピードコントロールに優れる全体技。',
    'train.type.h2':  'タイプ相性一覧',
    'train.type.p1':  'でんき・ひこうの複合タイプによるタイプ相性です。「ふゆう」により地面技も無効になる点に注意。',
    'train.type.note': '※いわタイプに4倍弱点を持つのが最大の弱点。いわなだれ・ストーンエッジには特に注意が必要です。',
    'train.summary.p': 'エモンガは種族値こそ低いですが、特性「ふゆう」と素早さ103、豊富な補助技を活かせば十分に戦力になるポケモンです。きあいのタスキを持たせた最速サポート型が最もオーソドックスで扱いやすい育成法です。ぜひあなただけのエモンガを育ててみてください！',

    // ステータス名（stat.）
    'stat.atk': 'こうげき',
    'stat.def': 'ぼうぎょ',
    'stat.spa': 'とくこう',
    'stat.spd': 'とくぼう',
    'stat.spe': 'すばやさ',

    // タイプ名（type.）
    'type.electric': 'でんき',
    'type.flying':   'ひこう',
    'type.normal':   'ノーマル',
    'type.ice':      'こおり',
    'type.rock':     'いわ',
    'type.ground':   'じめん',
    'type.grass':    'くさ',
    'type.fighting': 'かくとう',
    'type.bug':      'むし',
    'type.steel':    'はがね',
    'type.other':    'その他',

    // 分類（cat.）
    'cat.special':  '特殊',
    'cat.physical': '物理',
    'cat.status':   '変化',
  },

  en: {
    // 共通ナビ・ヘッダー
    'nav.top':          'Top',
    'nav.builds':       'Team Articles',
    'nav.regulation':   'Regulations',
    'nav.tournament':   'Tournaments',
    'nav.beginner':     'For Beginners',
    'header.search':    '🔍　Search',
    'header.tagline':   'Pokémon Team Media',

    // トップバー
    'topbar.tagline': '⚡ Pokémon VGC Team Media — For those captivated by Emolga',

    // index.html ヒーロー
    'hero.tag':   '⚡ NEW POST — Regulation J',
    'hero.h1':    'A Reborn <em>Team Showcase</em> Site',
    'hero.desc':  'An innovative sun team built around the Electric-type Emolga. The full story of a strategy that outplayed the meta to reach the top.',
    'hero.btn1':  '⚡ Read Article',
    'hero.btn2':  'Team Articles →',

    // index.html セクション
    'section.featured': 'Featured Articles',
    'section.seeall':   'See all →',
    'section.latest':   'Latest Articles',
    'section.more':     'More →',

    // カテゴリタブ
    'cat.all':        'All',
    'cat.wcs':        'WCS2026',
    'cat.official':   'Official Events',
    'cat.grassroots': 'Grassroots',
    'cat.online':     'Online',
    'cat.offline':    'Offline',

    // 記事カード：article-wcs2026
    'art1.reg':    '⚡ Regulation J',
    'art1.title':  '[WCS2026 Qualifier] Full Team Reveal: Emolga × Kyogre Rain Team That Aimed for the World Stage',
    'art1.desc':   'A team that maximizes the synergy of Emolga\'s Levitate and Electric moves.',
    'art1.author': 'Emotaro · 2026.05.01',

    // 記事カード：article-gorilla
    'art2.title': 'Emolga × Rillaboom Electric-Grass Team — Reaching Rating 2000',
    'art2.meta':  '⚡ Kaminari · 2026.04.28',

    // 記事カード：article-trick
    'art3.title': '[TeruChalle Champion] Full Reveal of Emolga Trick Room Team',
    'art3.meta':  '⚡ emonga_game · 2026.04.22',

    // 記事カード：article-pjcs
    'art4.title': 'PJCS2026 Qualifier Top Team Roundup — 15% Emolga Usage Shocks the Scene',
    'art4.meta':  'Editorial · 2026.04.18',

    // 記事カード：article-training
    'art5.title': '[Definitive Guide] Complete Emolga EV Training Guide — All Spreads, Items & Movesets',
    'art5.meta':  'Dr. Emonga · 2026.04.10',

    // tournament.html
    'tournament.hero.h1':   '🏆 Tournament Info',
    'tournament.hero.desc': 'Results and schedules for official and grassroots tournaments. Click a tournament name to view details.',
    'tournament.ongoing':   '📅 Ongoing & Upcoming',
    'tournament.recent':    '📊 Recent Results',

    // サイドバー
    'sidebar.about.title':   'About New Emolgame',
    'sidebar.about.desc':    'A Pokémon team showcase blog by players who love Emolga. We cover the forefront of VGC Double Battles.',
    'sidebar.ranking.title': 'Popular Articles',
    'sidebar.tags.title':    'Tags',
    'sidebar.twitter.title': 'Twitter / X',
    'sidebar.twitter.desc':  'Follow us for updates',
    'sidebar.twitter.btn':   'Follow →',

    // フッター
    'footer.desc':     'A Pokémon team showcase media for trainers captivated by Emolga.',
    'footer.content':  'Content',
    'footer.siteinfo': 'Site Info',
    'footer.contact':  'Contact',
    'footer.privacy':  'Privacy Policy',
    'footer.about':    'About Us',

    // 検索
    'search.placeholder': 'Search by title or Pokémon name…',
    'search.hint':        'Enter a keyword to search',
    'search.noresult':    'No articles found for',

    // builds.html
    'builds.hero.h1':   '📖 Team Articles',
    'builds.hero.desc': 'Browse all team articles. Filter by regulation or tournament.',
    'builds.section':   '📋 All Team Articles',

    // regulation.html
    'reg.hero.h1':   '📋 Regulations',
    'reg.hero.desc': 'Current and past VGC regulations explained.',

    // beginner.html
    'beginner.hero.h1':   '🔰 Beginner\'s Guide',
    'beginner.hero.desc': 'An introductory guide for those starting out in Double Battles.',

    // article 共通
    'article.back':               '← Back to Articles',
    'article.breadcrumb.builds':  'Team Articles',
    'article.concept':            'Team Concept',
    'article.members':            'Team Members',
    'article.strategy':           'Strategy',
    'article.results':            'Tournament Results',
    'article.summary':            'Summary',

    // バッジ共通
    'badge.regj':     'Reg.J',
    'badge.team':     'Team',
    'badge.event':    'Tournament',
    'badge.official': 'Official',
    'badge.wcs':      'WCS2026',
    'badge.iku':      'EV Guide',
    'badge.begin':    'Intro',

    // index.html サイドバー stats
    'sidebar.stats.builds':    'Team Articles',
    'sidebar.stats.events':    'Tournament Results',
    'sidebar.stats.pv':        'Monthly PV',
    'sidebar.stats.followers': 'Followers',

    // builds.html 注目カード
    'builds.featured.head':   'Featured Team',
    'builds.featured.badge':  '🏆 WCS2026 Qualifier',
    'builds.featured.reg':    '⚡ Regulation J',
    'builds.featured.title':  '[WCS2026 Qualifier] Emolga × Kyogre Rain Team',
    'builds.featured.desc':   'A team leveraging Emolga\'s Levitate and Electric Engine with Kyogre\'s Drizzle for Thunder spam. Full breakdown of leads and strategy.',
    'builds.featured.author': 'Emotaro · 2026.05.01',
    'builds.info':            '💡 <strong>How to read team articles:</strong> Each article covers pick rationale, EV spreads, movesets, and lead patterns. New to VGC? Check the <a href="beginner.html" style="color:var(--sky-dark);font-weight:600;">Beginner\'s Guide</a> first!',

    // builds.html 記事カード
    'builds.card1.title': 'Emolga × Rillaboom Electric-Grass Team — Rating 2000 Milestone',
    'builds.card2.title': '[TeruChalle Champion] Full Emolga Trick Room Team Reveal',
    'builds.card3.title': 'PJCS2026 Qualifier Top Teams Roundup — 15% Emolga Usage',
    'builds.card4.title': '[Definitive Guide] Complete Emolga EV Training — All Spreads, Items & Movesets',
    'builds.card5.title': 'WCS2026 Qualification! Full Record of Emolga Core Balanced Team',
    'builds.card6.title': 'Emolga × Flutter Mane Electric-Fairy Team — Season Final Rating 2100',

    // builds.html サイドバー
    'builds.sidebar.about':      'About Team Articles',
    'builds.sidebar.about.desc': 'We break down real competitive teams with full lead patterns, strategies, and post-analysis!',
    'builds.sidebar.tags':       'Filter by Tag',
    'builds.twitter.req':        'Send team requests on Twitter!',
    'builds.cta':                'New team articles added regularly! Follow us on Twitter for the latest updates.',

    // regulation.html 本文・サイドバー追加キー
    'reg.breadcrumb':            'Top > Regulations',
    'reg.info':                  '⚡ <strong>Emolga is usable in Regulation J!</strong> It stands out as the only Electric/Flying-type Pokémon of its kind.',
    'reg.current.head':          'Current Regulation',
    'reg.regj.title':            '🔥 Regulation J (Current)',
    'reg.regj.status':           'NOW',
    'reg.regj.desc':             'The latest regulation for Pokémon Scarlet and Violet. Some Paradox Pokémon and sub-legendary Pokémon are now permitted, giving rise to diverse team compositions. Emolga builds leveraging the Electric Engine ability are drawing attention.',
    'reg.regj.date':             '📅 January 2026 ~',
    'reg.regj.format':           '👥 Double Battle',
    'reg.regj.emolga':           '⚡ Emolga Allowed',
    'reg.regj.wcs':              '🏆 WCS2026 Format',
    'reg.emolga.head':           'Why Use Emolga?',
    'reg.emolga.name':           'Emolga (No.587)',
    'reg.emolga.types':          'Electric / Flying type — Levitate / Static / Electric Engine',
    'reg.type.electric':         'Electric',
    'reg.type.flying':           'Flying',
    'reg.table.stat':            'Stat',
    'reg.table.base':            'Base',
    'reg.table.note':            'Notes',
    'reg.stat.hp':               'HP',
    'reg.stat.atk':              'Atk',
    'reg.stat.def':              'Def',
    'reg.stat.spa':              'SpA',
    'reg.stat.spd':              'SpD',
    'reg.stat.spe':              'Spe',
    'reg.emolga.trait':          'Base 103 Speed is quite respectable. The biggest appeal is Electric Engine — when hit by an Electric move, Attack rises 2 stages! Receiving an ally\'s Thunder to aim for a sweep is a powerful tactic.',
    'reg.past.head':             'Past Regulations',
    'reg.status.past':           'Ended',
    'reg.regi.title':            'Regulation I',
    'reg.regi.desc':             'The regulation that unlocked Paradox Pokémon. Emolga frequently shone through its synergy with Raging Bolt.',
    'reg.regi.date':             '📅 June – December 2025',
    'reg.regi.emolga':           '⚡ Emolga Allowed',
    'reg.regh.title':            'Regulation H',
    'reg.regh.desc':             'The regulation that unlocked restricted legendaries. The Emolga + Kyogre combo drew significant attention.',
    'reg.regh.date':             '📅 January – May 2025',
    'reg.regh.emolga':           '⚡ Emolga Allowed',
    'reg.cta':                   'View Team Articles →',
    'reg.sidebar.quickref':      'Regulation Quick Reference',
    'reg.sidebar.quickref.desc': 'Emolga is usable in every regulation!',
    'reg.sidebar.rules':         'Current Rules',
    'reg.rule.allowed':          '✅ Allowed: Regulation J eligible Pokémon',
    'reg.rule.banned':           '❌ Banned: Some restricted legendaries',
    'reg.rule.format':           '👥 Format: Double Battle',
    'reg.rule.time':             '⏱️ Time Limit: 7 minutes',
    'reg.sidebar.related':       'Related Pages',
    'reg.link.builds':           '→ Reg.J Team List',
    'reg.link.tournament':       '→ Tournament Info & Schedule',
    'reg.link.beginner':         '→ Learn the Basics',
    'reg.twitter.desc':          'Rule changes announced on Twitter first!',

    // beginner.html 本文・サイドバー追加キー
    'beg.breadcrumb':            'Top > For Beginners',
    'beg.guide.title':           '⚡ Get Stronger with Emolga!',
    'beg.guide.desc':            'Does Pokémon Double Battle seem intimidating? Don\'t worry! This page breaks it all down from the basics. Let\'s start by getting to know Emolga\'s charm!',
    'beg.steps.head':            '🚀 Double Battle Intro — 5 Steps',
    'beg.step1.title':           'What is Double Battle?',
    'beg.step1.desc':            'Double Battle is a format where both players put two Pokémon on the field at once. Unlike Single Battles, <strong>coordination between two Pokémon</strong> is key. For example, Emolga uses Thunder, and an ally with Electric Engine gets powered up — that\'s the kind of combo that makes Doubles exciting!',
    'beg.step2.title':           'Building Your Party (Team)',
    'beg.step2.desc':            'The six Pokémon you bring to a match are your "party." You choose four to lead with, and only two battle at a time. Try to think about type balance and role distribution! Emolga is Electric/Flying-type and can fit into many team compositions.',
    'beg.step3.title':           'Understanding EVs and IVs',
    'beg.step3.desc':            'Pokémon have "Effort Values (EVs)" and "Individual Values (IVs)" that greatly affect their stats depending on how they\'re trained! The standard Emolga EV spread puts <strong>252 in Atk or SpA and 252 in Speed</strong>. Our training guide articles explain this in detail!',
    'beg.step4.title':           'Weather and Field Effects',
    'beg.step4.desc':            'Weather such as "Rain" (Drizzle) and "Sun" (Drought) greatly affects move power and specific strategies. In an Emolga × Kyogre "Rain Team," Rain makes <strong>Thunder\'s accuracy 100%</strong>! Learning these combinations expands your teambuilding options.',
    'beg.step5.title':           'Actually Battle!',
    'beg.step5.desc':            'Try entering Ranked Battles or online tournaments! You may lose a lot at first, but that\'s the fastest path to improvement. Use <strong>our team articles</strong> as a reference while building your own unique party!',
    'beg.qa.head':               '❓ Frequently Asked Questions (FAQ)',
    'beg.qa1.q':                 'Is Emolga any good competitively?',
    'beg.qa1.a':                 'Its base stats aren\'t outstanding, but the ability "Electric Engine" is incredibly unique! When hit by an ally\'s Electric move, its Attack rises 2 stages, enabling explosive damage output. Master it and it can absolutely perform in competitive play!⚡',
    'beg.qa2.q':                 'Can beginners understand the team articles?',
    'beg.qa2.a':                 'We strive to explain everything in as clear language as possible. When jargon appears, we explain it in the FAQ section on this page, so please feel free to refer to it!',
    'beg.qa3.q':                 'What do "lead" and "strategy/gameplay" mean?',
    'beg.qa3.a':                 '"Lead" (選出) means choosing 4 Pokémon from your 6 to actually use. "Strategy/gameplay" (立ち回り) refers to the decisions you make each turn during a match. Team articles explain "which Pokémon to lead against this team" and "how to play the early game" in detail!',
    'beg.qa4.q':                 'What is a Regulation?',
    'beg.qa4.a':                 'It\'s the official ruleset determining which Pokémon can be used in official tournaments. Currently "Regulation J" is the latest, with a defined list of usable Pokémon. Emolga is usable in every regulation! See the <a href="regulation.html" style="color:var(--sky-dark);">Regulations page</a> for details.',
    'beg.qa5.q':                 'How do I enter a tournament?',
    'beg.qa5.a':                 'Official tournaments can be entered via the Pokémon HOME app or the Pokémon Trainer\'s Website. Grassroots tournaments announce participation details on the organizer\'s Twitter or Discord. Our <a href="tournament.html" style="color:var(--sky-dark);">Tournament Info page</a> also compiles information!',
    'beg.articles.head':         '📚 Recommended Articles for Beginners',
    'beg.rec1.title':            '[Definitive Guide] Complete Emolga EV Training — All Spreads, Items & Movesets',
    'beg.rec2.title':            'Your First Double Battle! A Beginner-Friendly Team You Can Win With Emolga',
    'beg.cta':                   'View All Team Articles →',
    'beg.sidebar.welcome':       'For New Players',
    'beg.sidebar.welcome.desc':  'Feel free to ask questions on Twitter too! We\'re a friendly community of Emolga fans.⚡',
    'beg.sidebar.toc':           'Intro Guide Contents',
    'beg.toc1':                  '① What is Double Battle?',
    'beg.toc2':                  '② Build Your Party',
    'beg.toc3':                  '③ EVs & IVs',
    'beg.toc4':                  '④ Weather & Field Effects',
    'beg.toc5':                  '⑤ Battle It Out!',
    'beg.sidebar.related':       'Related Pages',
    'beg.link.builds':           '→ Read Team Articles',
    'beg.link.regulation':       '→ Check Regulations',
    'beg.link.tournament':       '→ Tournament Info',
    'beg.twitter.title':         'Questions? Ask on Twitter!',
    'beg.twitter.desc':          'Beginner questions are always welcome!',

    // ポケモン名（poke.）
    'poke.emolga':      'Emolga',
    'poke.kyogre':      'Kyogre',
    'poke.volcarona':     'Volcarona',
    'poke.landorus':      'Landorus (Therian)',
    'poke.gardevoir':     'Gardevoir',
    'poke.incineroar':    'Incineroar',
    'poke.rillaboom':     'Rillaboom',
    'poke.urshifu':       'Urshifu (Single Strike)',
    'poke.urshifurapid':  'Urshifu (Rapid Strike)',
    'poke.porygon2':      'Porygon2',
    'poke.torkoal':       'Torkoal',
    'poke.mimikyu':       'Mimikyu',
    'poke.rhyperior':     'Rhyperior',
    'poke.fluttermane':   'Flutter Mane',
    'poke.indeedee':      'Indeedee',
    'poke.miraidon':      'Miraidon',

    // 技名（move.）
    'move.discharge':     'Discharge',
    'move.thunderwave':   'Thunder Wave',
    'move.acrobatics':    'Acrobatics',
    'move.protect':       'Protect',
    'move.waterspout':    'Water Spout',
    'move.surf':          'Surf',
    'move.thunder':       'Thunder',
    'move.icywind':       'Icy Wind',
    'move.fireblast':     'Fire Blast',
    'move.gigadrain':     'Giga Drain',
    'move.quiverdance':   'Quiver Dance',
    'move.earthquake':    'Earthquake',
    'move.rockslide':     'Rock Slide',
    'move.fly':           'Fly',
    'move.uturn':         'U-turn',
    'move.psychic':       'Psychic',
    'move.moonblast':     'Moonblast',
    'move.trickroom':     'Trick Room',
    'move.flareblitz':    'Flare Blitz',
    'move.darkestlariat': 'Darkest Lariat',
    'move.knockoff':      'Knock Off',
    'move.fakeout':       'Fake Out',
    'move.woodhammer':    'Wood Hammer',
    'move.grassyglide':   'Grassy Glide',
    'move.closecombat':   'Close Combat',
    'move.encore':        'Encore',
    'move.shadowball':    'Shadow Ball',
    'move.bulldoze':      'Bulldoze',
    'move.thunderbolt':   'Thunderbolt',
    'move.eruption':      'Eruption',
    'move.helpinghand':   'Helping Hand',
    'move.triattack':     'Tri Attack',
    'move.foulplay':      'Foul Play',
    'move.recover':       'Recover',
    'move.shadowclaw':    'Shadow Claw',
    'move.shadowsneak':   'Shadow Sneak',
    'move.stoneedge':     'Stone Edge',
    'move.iceshard':      'Ice Shard',
    'move.irontail':      'Iron Tail',
    'move.wildcharge':    'Wild Charge',
    'move.drillpeck':     'Drill Peck',
    'move.mysticalfire':  'Mystical Fire',
    'move.wickedblow':    'Wicked Blow',
    'move.surgingstrikes':'Surging Strikes',

    // 持ち物（item.）
    'item.focussash':   'Focus Sash',
    'item.choicespecs': 'Choice Specs',
    'item.lifeorb':     'Life Orb',
    'item.choicescarf': 'Choice Scarf',
    'item.silkscarf':   'Silk Scarf',
    'item.assaultvest': 'Assault Vest',
    'item.leftovers':   'Leftovers',
    'item.sitrus':      'Sitrus Berry',
    'item.miracleseed': 'Miracle Seed',
    'item.eviolite':    'Eviolite',

    // 特性（ability.）
    'ability.levitate':       'Levitate',
    'ability.drizzle':        'Drizzle',
    'ability.flamebody':      'Flame Body',
    'ability.intimidate':     'Intimidate',
    'ability.trace':          'Trace',
    'ability.blaze':          'Blaze',
    'ability.grassysurge':    'Grassy Surge',
    'ability.drought':        'Drought',
    'ability.protosynthesis': 'Protosynthesis',
    'ability.unseenfist':     'Unseen Fist',
    'ability.download':       'Download',
    'ability.disguise':       'Disguise',
    'ability.solidrock':      'Solid Rock',
    'ability.tangledfeet':    'Tangled Feet',

    // テーブルヘッダー（共通）
    'table.pokemon': 'Pokémon',
    'table.item':    'Item',
    'table.ability': 'Ability',
    'table.moves':   'Moveset',
    'table.evs':     'EVs',

    // article-wcs2026.html
    'wcs.title':    '[WCS2026 Qualifier] Full Team Reveal: Emolga × Kyogre Rain Team',
    'wcs.badge1':   '🏆 WCS2026 Qualifier',
    'wcs.badge2':   '⚡ Regulation J',
    'wcs.badge3':   'Rain Team',
    'wcs.breadcrumb': '[WCS2026 Qualifier] Emolga × Kyogre Rain Team',
    'wcs.concept.p': 'The core synergy of this team is Emolga\'s Levitate nullifying Ground-type moves, combined with Kyogre\'s Drizzle boosting Electric moves. Although Rain does not directly increase the power of Emolga\'s Discharge or Thunderbolt, Kyogre\'s overwhelming Special Attack and the Electric-type\'s consistency become the springboard for breaking apart opposing teams. This team exploits unexpected plays in the WCS2026 head-to-head environment.',
    'wcs.strategy.p1.title': 'Pattern 1: Emolga + Kyogre — Opening Rain Setup',
    'wcs.strategy.p1.desc':  'The most fundamental lead. While Kyogre activates Drizzle, Emolga supports with Thunder Wave. The biggest strength is Kyogre\'s Thunder hitting at 100% accuracy in Rain. Emolga\'s Acrobatics is held in reserve to handle opposing Incineroar.',
    'wcs.strategy.p2.title': 'Pattern 2: Incineroar + Emolga — Fake Out Control',
    'wcs.strategy.p2.desc':  'Incineroar moves first before the opponent can use Fake Out, allowing Emolga to act safely. The switch plan of having Emolga use Protect while landing Kyogre from the back is highly effective.',
    'wcs.strategy.p3.title': 'Pattern 3: Landorus + Gardevoir — Anti-Trick Room',
    'wcs.strategy.p3.desc':  'When the opponent targets a Trick Room setup, Landorus\'s Intimidate suppresses the physical side while Gardevoir sets up Trick Room first, flipping it back as a counter-Trick Room reversal.',
    'wcs.strategy.p4.title': 'Pattern 4: Volcarona + Emolga — Electric-Fire Combo',
    'wcs.strategy.p4.desc':  'The combo used for closing out games. After Volcarona boosts with Quiver Dance, Emolga follows up with Discharge. Volcarona\'s Fire moves and Emolga\'s Electric moves cover a wide range of types.',
    'wcs.results.box1.label': 'Swiss Record (9 rounds)',
    'wcs.results.box2.label': 'Final Placement',
    'wcs.results.box3.label': 'WCS2026 Points Earned',
    'wcs.results.box4.label': 'Emolga Lead Rate',
    'wcs.results.p':  'Finished 7-2 in Swiss to sneak into TOP16 and secure a spot in the main bracket. The run ended at Top 16, but earning 3 WCS points became a solid stepping stone toward a World Championship invitation. Emolga was selected in 78% of matches, proving its high matchup capability.',
    'wcs.summary.p':  'The seemingly unconventional Emolga × Kyogre pairing produced far greater synergy than expected. This tournament reminded me once again of the importance of metagame reads and thorough preparation. We\'ll keep refining the team with the WCS main event in mind. Onward to the World Stage with Emolga!',

    // article-gorilla.html
    'gorilla.title':    'Emolga × Rillaboom Electric-Grass Team — Reaching Rating 2000',
    'gorilla.badge1':   '🌿 Electric-Grass Team',
    'gorilla.badge2':   '⚡ Regulation J',
    'gorilla.badge3':   'Rating 2000 Achieved',
    'gorilla.breadcrumb': 'Emolga × Rillaboom Electric-Grass Team — Reaching Rating 2000',
    'gorilla.concept.p': 'An "Electric-Grass" team that takes full advantage of the type synergy between Emolga and Rillaboom. Rillaboom\'s Grassy Surge sets up Grassy Terrain to power up Grass moves, while Emolga\'s Electric moves provide wide coverage. The strategy reduces Ground-type damage through the field while forcing narrow team selection with the strong consistency of Electric and Grass types. This is the commemorative team reveal after achieving the milestone of Rating 2000 in the season\'s Ranked Battles.',
    'gorilla.strategy.p1.title': 'Pattern 1: Rillaboom + Emolga — Grassy Terrain Setup',
    'gorilla.strategy.p1.desc':  'Rillaboom sets up Grassy Terrain via Grassy Surge while Emolga provides support with Thunder Wave. Grassy Terrain halves Earthquake damage, and combined with Emolga\'s Levitate nullifying Ground moves, a double layer of protection is established.',
    'gorilla.strategy.p2.title': 'Pattern 2: Porygon2 + Rillaboom — Stall Expansion',
    'gorilla.strategy.p2.desc':  'A build that uses Porygon2\'s Helping Hand to power up Rillaboom\'s Grassy Glide. Porygon2 acts as a wall with the bulk provided by Eviolite, while Rillaboom chips away at the opponent with its boosted Grass move.',
    'gorilla.strategy.p3.title': 'Pattern 3: Urshifu + Landorus — Late-Game Sweep',
    'gorilla.strategy.p3.desc':  'A combo dropped in during the late game after reading the opponent\'s team composition early. Landorus\'s Intimidate weakens physical attackers, then Urshifu sweeps through targets that have been knocked into KO range, forcing a cleanup.',
    'gorilla.summary.p': 'Achieving the goal of Rating 2000 was thanks to the Grassy Terrain and Emolga\'s Ground immunity combination hitting the meta just right. The Rillaboom and Emolga lead is hard to counter, and it\'s a team I want to keep refining. Next goal: Rating 2100!',

    // article-trick-room.html
    'trick.title':    '[TeruChalle Champion] Full Reveal of the Emolga Trick Room Team',
    'trick.badge1':   '🏆 TeruChalle Champion',
    'trick.badge2':   'Trick Room',
    'trick.badge3':   'Grassroots Event',
    'trick.breadcrumb': '[TeruChalle Champion] Full Reveal of the Emolga Trick Room Team',
    'trick.concept.p': 'This team was built to overturn the conventional wisdom that "Emolga doesn\'t fit in Trick Room teams." While Emolga itself struggles to act under Trick Room, by clearly defining its roles — supporting the Trick Room setup and shining on normal-speed turns outside of Trick Room — it functions as a vital cog in the machine. This is the full reveal to commemorate winning the TeruChalle (TeruAccount-hosted Challenge Cup) with a perfect record.',
    'trick.strategy.p1.title': 'Pattern 1: Mimikyu + Porygon2 — Dual Trick Room Setup',
    'trick.strategy.p1.desc':  'Mimikyu tanks a hit using Disguise and sets up Trick Room, then Porygon2\'s Helping Hand supports Rhyperior. Because both Pokémon can set Trick Room independently, the pair is resistant to interference from the opponent.',
    'trick.strategy.p2.title': 'Pattern 2: Emolga + Rhyperior — Support on Normal Turns',
    'trick.strategy.p2.desc':  'On turns outside of Trick Room, Emolga paralyzes the opponent with Thunder Wave while Rhyperior attacks. Emolga\'s Encore locking down the opponent\'s setup moves or support moves is especially powerful.',
    'trick.strategy.p3.title': 'Pattern 3: Flutter Mane + Emolga — Reverse Fast Mode',
    'trick.strategy.p3.desc':  'A backup plan prepared for when Trick Room is reversed or disrupted. Flutter Mane moves at high speed while Emolga controls speed with Thunder Wave, steering the matchup in a favorable direction.',
    'trick.strategy.p4.title': 'Pattern 4: Kilowattrel + Rhyperior — Slow Synergy',
    'trick.strategy.p4.desc':  'The main combo under Trick Room. Kilowattrel\'s Bulldoze drops speed, then Rhyperior covers the field with Earthquake. Kilowattrel\'s Hustle fooling the opponent\'s reads is the key element.',
    'trick.results.box1.label': 'TeruChalle Swiss',
    'trick.results.box2.label': 'Final Result',
    'trick.results.box3.label': 'Participants',
    'trick.results.box4.label': 'Emolga Lead Rate',
    'trick.results.p':  'Won the TeruChalle with 32 participants, going undefeated from Swiss to Finals (6-0). Emolga\'s Thunder Wave and Encore shone throughout, with its ability to lock down opponent actions standing out in every game.',
    'trick.summary.p':  'Emolga is often thought to be a poor fit for Trick Room, but it proved to be an excellent support Pokémon. Shutting down opponent support moves with Encore was especially impactful and was the biggest factor in winning the tournament. The potential of Emolga is limitless!',

    // article-pjcs2026.html
    'pjcs.title':    'PJCS2026 Qualifier Top Team Roundup — 15% Emolga Usage Shocks the Scene',
    'pjcs.badge1':   '🏆 PJCS2026',
    'pjcs.badge2':   'Tournament Recap',
    'pjcs.badge3':   '15% Emolga Usage',
    'pjcs.breadcrumb': 'PJCS2026 Qualifier Top Team Roundup — 15% Emolga Usage Shocks the Scene',
    'pjcs.intro.h2':  'Introduction',
    'pjcs.intro.p':   'The editorial team independently compiled team usage data from the top 16 players at the Pokémon Japan Championship Series 2026 (PJCS2026) Qualifier held in April 2026. The most noteworthy result this time is that Emolga\'s usage rate reached 15% — 5 out of the top 16 players used it. The fact that this many top players used Emolga in recent VGC Double Battle formats is arguably an all-time high, signaling a shift in the metagame.',
    'pjcs.overview.h2':  'Tournament Overview',
    'pjcs.overview.box1.label': 'Participants',
    'pjcs.overview.box2.label': 'Swiss Rounds',
    'pjcs.overview.box3.label': 'Top Cut',
    'pjcs.overview.box4.label': 'Emolga Usage (Top 16)',
    'pjcs.usage.h2':   'Top 10 Most-Used Pokémon',
    'pjcs.usage.th1':  'Rank',
    'pjcs.usage.th2':  'Pokémon',
    'pjcs.usage.th3':  'Count (/16)',
    'pjcs.usage.th4':  'Usage Rate',
    'pjcs.usage.note': '* Excluding reserve-slot Pokémon outside the tallied data, Emolga effectively ranks in the Top 10 — its highest placement ever.',
    'pjcs.emolga.h2':  'Team Themes of the 5 Emolga Users',
    'pjcs.emolga.th1': 'Placement',
    'pjcs.emolga.th2': 'Player',
    'pjcs.emolga.th3': 'Team Theme',
    'pjcs.emolga.th4': 'Emolga\'s Role',
    'pjcs.results.box1.label': 'Emolga Users (of Top 16)',
    'pjcs.results.box2.label': 'Best Placement by Emolga User',
    'pjcs.results.box3.label': 'More Users vs. Last Year',
    'pjcs.results.box4.label': 'Top Usage Rate (All-Time High)',
    'pjcs.results.p':  'The top finish rate of Emolga users was remarkably high — 3 out of 5 placed in the Top 8. This is no coincidence; it demonstrates that Emolga\'s Levitate and Thunder Wave are directly countering the dominant Kyogre + Landorus core in the current metagame.',
    'pjcs.summary.p':  'Emolga recording a 15% usage rate among the top finishers at the PJCS2026 Qualifier marks a new chapter in Pokémon competitive history. Now that Emolga — long dismissed as "unusable" — has broken into the metagame, we look forward to more active research into Emolga-centered team building.',

    // article-training.html
    'train.title':    '[Definitive Guide] Complete Emolga Training Guide — All EV Spreads, Items & Movesets',
    'train.badge1':   'Definitive Guide',
    'train.badge2':   'Training Guide',
    'train.badge3':   'For Beginners',
    'train.breadcrumb': '[Definitive Guide] Complete Emolga Training Guide — All EV Spreads, Items & Movesets',
    'train.base.h2':  'Emolga Base Data',
    'train.base.p1':  'Emolga (No.587) is an Electric/Flying-type bipedal squirrel Pokémon. Its greatest feature is the ability Levitate, which grants complete immunity to Ground-type moves. Its base stat total of 472 is modest, but a standout Speed of 103 allows it to fit into a wide variety of teams as a support Pokémon.',
    'train.base.ability': 'Ability: Levitate (immune to Ground-type moves, Bulldoze, and Mud Shot) / Motor Drive (unused)',
    'train.base.type': 'Type: Electric / Flying',
    'train.ev.h2':    '5 EV Spread Patterns',
    'train.ev.p':     'Here are 5 EV spread patterns tailored to Emolga\'s different roles.',
    'train.ev.th.name':    'Spread Name',
    'train.ev.th.rec':     'Rating',
    'train.ev.th.usage':   'Usage',
    'train.ev.build1.name': 'Max Speed Attacker',
    'train.ev.build1.usage': 'Max Speed / Max Special Attack',
    'train.ev.build2.name': 'Full Support',
    'train.ev.build2.usage': 'Thunder Wave / Encore Support',
    'train.ev.build3.name': 'Bulky Support',
    'train.ev.build3.usage': 'No Focus Sash Needed',
    'train.ev.build4.name': 'Physical Attacker',
    'train.ev.build4.usage': 'Acrobatics / U-turn',
    'train.ev.build5.name': 'Moderate Speed Bulky',
    'train.ev.build5.usage': 'End-game Wall',
    'train.item.h2':  'Item Candidates',
    'train.item1.name': 'Focus Sash ★ Top Recommendation',
    'train.item1.desc': 'Survives any KO hit with 1 HP remaining. Compensates for Emolga\'s low bulk, guaranteeing at least one action. A versatile item usable on both support and attacker builds.',
    'train.item2.name': 'Electric Seed',
    'train.item2.desc': 'Intended to combo with Acrobatics. After consuming the seed, Acrobatics doubles in power to 110. The go-to choice for physical Emolga builds, though the seed must be held at the start of the turn.',
    'train.item3.name': 'Choice Scarf',
    'train.item3.desc': 'Boosts Speed by 1.5×. Pushes Max Speed Emolga\'s base 103 Speed even higher, letting it outspeed fast threats in the current metagame. The downside is being locked into one move.',
    'train.item4.name': 'Life Orb',
    'train.item4.desc': 'Boosts move power by 1.3×. Gives attacker Emolga extra firepower for its Electric moves. Weigh the HP recoil against the benefits compared to Focus Sash when building.',
    'train.item5.name': 'Sitrus Berry',
    'train.item5.desc': 'Restores HP when it drops below half. Functions as a bulk aid when not running Focus Sash, suiting support builds that need to survive multiple turns.',
    'train.move.h2':       'All Moveset Patterns',
    'train.move.main.h3':  'Main Moves (Electric / Flying)',
    'train.move.sub.h3':   'Support Moves',
    'train.move.th.name':  'Move',
    'train.move.th.type':  'Type',
    'train.move.th.cat':   'Category',
    'train.move.th.power': 'Power',
    'train.move.th.acc':   'Acc.',
    'train.move.th.pri':   'Priority',
    'train.move.th.desc':  'Description',
    'train.move.discharge.desc': 'Hits both opponents; 30% paralysis chance. The main spread move that reaches both sides in Double Battles.',
    'train.move.thunderbolt.desc': 'Single-target Electric main move. High power with reliable accuracy, easy to use.',
    'train.move.thunder.desc': '100% accuracy in Rain. Enormous synergy with Kyogre makes it highly worth adopting.',
    'train.move.acrobatics.desc': 'Power doubles when the user holds no item. Reaches 110 power after the Electric Seed is consumed.',
    'train.move.uturn.desc': 'Switches out after dealing damage. Used in combination with pivot tactics.',
    'train.move.thunderwave.desc': 'Inflicts paralysis on the target. Halves Speed, allowing strong speed control over faster Pokémon.',
    'train.move.encore.desc': 'Forces the target to repeat its last move for 3 turns. Shuts down setup moves and Trick Room.',
    'train.move.protect.desc': 'Blocks all moves for the turn. An essential survival and turn-management move in Double Battles.',
    'train.move.icywind.desc': 'Lowers the Speed of all targets by one stage. A spread speed-control move with excellent utility.',
    'train.type.h2':  'Type Matchup Chart',
    'train.type.p1':  'Type matchups for the Electric/Flying dual type. Note that Levitate also makes Ground moves completely ineffective.',
    'train.type.note': '* The 4× weakness to Rock is the biggest liability. Watch out especially for Rock Slide and Stone Edge.',
    'train.summary.p': 'Emolga\'s base stats may be unimpressive, but by leveraging Levitate, its base 103 Speed, and its broad support movepool, it can absolutely pull its weight. The Max Speed support build with Focus Sash is the most orthodox and easy-to-use approach. Go ahead and raise your very own Emolga!',

    // ステータス名（stat.）
    'stat.atk': 'Atk',
    'stat.def': 'Def',
    'stat.spa': 'SpA',
    'stat.spd': 'SpD',
    'stat.spe': 'Spe',

    // タイプ名（type.）
    'type.electric': 'Electric',
    'type.flying':   'Flying',
    'type.normal':   'Normal',
    'type.ice':      'Ice',
    'type.rock':     'Rock',
    'type.ground':   'Ground',
    'type.grass':    'Grass',
    'type.fighting': 'Fighting',
    'type.bug':      'Bug',
    'type.steel':    'Steel',
    'type.other':    'Other',

    // 分類（cat.）
    'cat.special':  'Special',
    'cat.physical': 'Physical',
    'cat.status':   'Status',
  }
};

function applyLang(lang) {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const text = TRANSLATIONS[lang]?.[key];
    if (text !== undefined) {
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        el.placeholder = text;
      } else {
        el.innerHTML = text;
      }
    }
  });
  // Toggle button label
  document.querySelectorAll('.lang-toggle').forEach(btn => {
    btn.textContent = lang === 'jp' ? 'EN' : 'JP';
  });
  // 色違いスワップ（EN→shiny, JP→通常）
  const SHINY_MAP = {
    'sprites/pokemon/587.png':
      'sprites/pokemon/shiny/587.png',
    'sprites/pokemon/other/official-artwork/587.png':
      'sprites/pokemon/other/official-artwork/shiny/587.png',
    'sprites/pokemon/other/home/587.png':
      'sprites/pokemon/other/home/shiny/587.png',
  };
  document.querySelectorAll('img[src*="587"]').forEach(img => {
    const src = img.getAttribute('src');
    if (lang === 'en') {
      for (const [normal, shiny] of Object.entries(SHINY_MAP)) {
        if (src.includes(normal)) { img.src = img.src.replace(normal, shiny); break; }
      }
    } else {
      for (const [normal, shiny] of Object.entries(SHINY_MAP)) {
        if (src.includes(shiny)) { img.src = img.src.replace(shiny, normal); break; }
      }
    }
  });
  localStorage.setItem('lang', lang);
  document.documentElement.lang = lang === 'jp' ? 'ja' : 'en';
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('lang') || 'jp';
  applyLang(saved);
  document.querySelectorAll('.lang-toggle').forEach(btn => {
    btn.addEventListener('click', () => {
      const current = localStorage.getItem('lang') || 'jp';
      applyLang(current === 'jp' ? 'en' : 'jp');
    });
  });
});
